# Generated by Django 2.1.7 on 2019-03-20 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('visit', '0001_initial'), ('visit', '0002_auto_20190216_1933'), ('visit', '0003_auto_20190219_0222'), ('visit', '0004_auto_20190219_0223'), ('visit', '0005_auto_20190223_0419')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_in_time', models.DateTimeField(blank=True, null=True)),
                ('sign_out_time', models.DateTimeField(blank=True, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Room')),
                ('notes', models.TextField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_targets', to=settings.AUTH_USER_MODEL)),
                ('sign_in_guardian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visit_signin_guardians', to=settings.AUTH_USER_MODEL)),
                ('sign_in_volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visit_signin_volunteers', to=settings.AUTH_USER_MODEL)),
                ('sign_out_guardian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visit_signout_guardians', to=settings.AUTH_USER_MODEL)),
                ('sign_out_volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visit_signout_volunteers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
