# Generated by Django 2.1.7 on 2019-02-16 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_targets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visit',
            name='originator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_originators', to=settings.AUTH_USER_MODEL),
        ),
    ]
