# Generated by Django 2.1.7 on 2019-02-19 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("visit", "0002_auto_20190216_1933"),
    ]

    operations = [
        migrations.RenameField(
            model_name="visit", old_name="sign_out", new_name="sign_out_time"
        ),
        migrations.RenameField(
            model_name="visit", old_name="sign_in", new_name="sign_in_time"
        ),
        migrations.RemoveField(model_name="visit", name="originator"),
        migrations.AddField(
            model_name="visit",
            name="sign_in_guardian",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visit_signin_guardians",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="sign_in_volunteer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visit_signin_volunteers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="sign_out_guardian",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visit_signout_guardians",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="sign_out_volunteer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visit_signout_volunteers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
