# Generated by Django 2.1.7 on 2019-02-19 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0003_auto_20190219_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='sign_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
