# Generated by Django 2.1.7 on 2019-02-23 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0004_auto_20190219_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Room'),
        ),
    ]
