entrypoint: gunicorn -b :$PORT kidcorral.wsgi:application
runtime: python37
env_variables:
  DB_TYPE: 'mysql'
  DB_PASSWORD: "securepass"
  DB_HOST: "gobetween1.company.com"
  DB_PORT: "3306"
handlers:
- url: /static
  static_dir: static
