# Generated by Django 2.1.7 on 2019-02-16 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='children',
            field=models.ManyToManyField(related_name='children', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='family',
            name='legal_guardians',
            field=models.ManyToManyField(related_name='legal_guardians', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='family',
            name='preferred_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_contact', to=settings.AUTH_USER_MODEL),
        ),
    ]
