# Generated by Django 2.1.7 on 2019-02-23 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='volunteer',
            field=models.BooleanField(default=False),
        ),
    ]
