# Generated by Django 2.1.7 on 2019-03-04 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_person_birthday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='birthday',
            new_name='birthdate',
        ),
    ]
