# Generated by Django 2.1.7 on 2019-02-16 18:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('families', '0002_auto_20190216_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='members',
        ),
        migrations.AddField(
            model_name='family',
            name='children',
            field=models.ManyToManyField(related_name='children', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='family',
            name='legal_guardians',
            field=models.ManyToManyField(related_name='legal_guardians', to=settings.AUTH_USER_MODEL),
        ),
    ]
